"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['ZCView.py']
DATA_FILES = [('', ['resources'])]
PY2APP_OPTIONS = {
    'argv_emulation': True,
    'optimize': 2,
    'iconfile': '/Users/driggs/workspace/zcview/resources/icons/myotisoft_icon.icns',
    'excludes': ['scipy', 'phonon', 'qt', 'PyQt4', 'PIL', 'PROJ'],
    'dylib_excludes': ['PyQT', 'QtCore', 'QtDeclarative', 'QtDesigner', 'QtGui', 'QtHelp', 'QtMultimedia', 'QtNetwork', 'QtOpenGL', 'QtScript', 'QtScriptTools', 'QtSql', 'QtSvg', 'QtTest', 'QtWebKit', 'QtXml', 'QtXmlPatterns',
                       'PROJ', 'PIL', 'phonon', '_codecs_cn.so', '_codecs_hk.so', '_codecs_iso2022.so', '_codecs_jp.so', '_codecs_kr.so', '_codecs_tw.so'],
    'matplotlib_backends': '-',  # only explicitly imported backends (wx)
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': PY2APP_OPTIONS},
    setup_requires=['py2app'],
)
